---
:git_url: https://github.com/funzoneq/OnMyWay.git
:playbook: playbook.yml
:baseurl: http://pxe.example.com
:image_server: http://192.168.1.1/mirror
:ubuntu_mirror: http://mirror.nl.leaseweb.net/ubuntu/
:initial_user: blendle
:initial_pass: root4me2
:initial_fullname: Blendle Baas
:recursive_dns: ['8.8.8.8', '4.2.2.2']
:ipv6_prefix: 2001:0DB8::